In [2]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,6,4,5])
new=arr[::-1]
print(new)

[5 4 6 3 2 1]


In [ ]:
array1=np.array([[1,2,3], [2,4,5], [1,2,3]])
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1=np.array([[1,2], [3,4]])
arr2=np.array([[1,2], [3,4]])
np.array_equal(arr1, arr2)
np.array_equiv(arr1, arr2)

True

In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg.sum())
print(np.sum(gfg, axis=0))
print(np.sum(gfg, axis=1))


45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [ ]:
n_array=np.array([[55,25,15], [30, 44, 2], [11, 45, 77]])
print(np.trace(n_array))
np.linalg.eig(n_array)

176


EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))

In [ ]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [ ]:
np.linalg.det(n_array)

np.float64(137180.0000000001)

In [ ]:
p=np.array([[1,2], [2, 3]])
q=np.array([[4,5], [6, 7]])
print(np.dot(p, q))
p2=np.array([[1,2], [2,3], [4,5]])
q2=np.array([[4,5,1], [6,7,2]])
np.cov(p.T, q.T)

[[16 19]
 [26 31]]


array([[0.5, 0.5, 1. , 1. ],
       [0.5, 0.5, 1. , 1. ],
       [1. , 1. , 2. , 2. ],
       [1. , 1. , 2. , 2. ]])

In [ ]:
x=np.array([[2, 3, 4], [3, 2, 9]])
y=np.array([[1,5,0], [5, 10, 13]])
print("Inner:", np.inner(x, y))
print("Outer:", np.outer(x, y))
print("Cartesian:", np.cross(x, y))

Inner: [[ 17  92]
 [ 13 152]]
Outer: [[  2  10   0  10  20  26]
 [  3  15   0  15  30  39]
 [  4  20   0  20  40  52]
 [  3  15   0  15  30  39]
 [  2  10   0  10  20  26]
 [  9  45   0  45  90 117]]
Cartesian: [[-20   4   7]
 [-64   6  20]]


In [ ]:
array=np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute: ", np.abs(array))
f=array.flatten();
print(np.percentile(f, 25))
print(np.percentile(f, 50))
print(np.percentile(f, 75))
print(f.mean())
print(np.median(f))
print(np.std(f))

Absolute:  [[1 2 3]
 [4 5 6]]
-3.5
-0.5
2.5
-0.5
-0.5
3.8622100754188224


In [ ]:
a=np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [3]:
array=np.array([10, 52, 62, 16, 16, 54, 453])
array.sort()
print(array)
np.sort(array)[:4]
np.sort(array)[-5:]

[ 10  16  16  52  54  62 453]


array([ 16,  52,  54,  62, 453])

In [6]:
array4=np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array4[array4==np.floor(array4)])
print(array4[array4!=np.ceil(array4)])

[1. 2. 3. 2.]
[1.2 2.2]
